#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Prod credentials never belong in the shared local-dev .env (that file's
# VITE_SUPABASE_URL/etc. point at the local `supabase start` stack). Record
# them in a separate, still-gitignored file instead (.env.* is ignored).
ENV_FILE=".env.production.local"

TOTAL_STAGES=9

banner "deploy-pipeline: production setup"
say "Bootstraps everything .github/workflows/deploy.yml needs that can't be"
say "scripted: a real Supabase project, a real Cloudflare Pages project, and"
say "the GitHub secrets/variables that connect them. See"
say ".scratch/deploy-pipeline/spec.md and its issues/01 ticket for the workflow"
say "itself, already written."
note "Run this from the repo root (uses \`gh\` against the current repo's origin)."

# ── Stage 1: Supabase production project ──────────────────────────────────
stage "Supabase: production project"
say "This is the real project deploy.yml pushes migrations/functions to —"
say "separate from the local supabase_db_legal_manager stack used by"
say "\`supabase start\`."
open_url "https://supabase.com/dashboard/projects"
step "If a production project for this app doesn't exist yet, click 'New project' and create one."
step "Otherwise, open the existing production project."
step "Its ref is in the URL: https://supabase.com/dashboard/project/<REF> — that <REF> is what you need."
ask SUPABASE_PROJECT_REF "Paste the project ref:"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"

# ── Stage 2: Supabase access token ─────────────────────────────────────────
stage "Supabase: CI access token"
say "A personal access token lets the CLI (and this wizard) act on your"
say "account without an interactive login."
open_url "https://supabase.com/dashboard/account/tokens"
step "Click 'Generate new token', name it something like 'legal-manager-ci'."
step "Copy it now — Supabase shows it exactly once."
ask_secret SUPABASE_ACCESS_TOKEN "Paste the access token:"
export SUPABASE_ACCESS_TOKEN

# ── Stage 3: Supabase DB password ──────────────────────────────────────────
stage "Supabase: database password"
say "Needed for 'supabase db push' to authenticate directly to Postgres."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/database"
step "If you set this when creating the project, use that password."
step "Otherwise click 'Reset database password' and copy the new one — also shown once."
ask_secret SUPABASE_DB_PASSWORD "Paste the database password:"

# ── Stage 4: Supabase client-safe API values ───────────────────────────────
stage "Supabase: API URL + anon key"
say "These get baked into the SPA build (client-safe, safe to expose)."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api"
step "Copy the 'Project URL'."
ask VITE_SUPABASE_URL_PROD "Paste the Project URL:"
step "Copy the 'anon' 'public' key."
ask_secret VITE_SUPABASE_ANON_KEY_PROD "Paste the anon public key:"
write_env VITE_SUPABASE_URL_PROD "$VITE_SUPABASE_URL_PROD"

# ── Stage 5: GROQ_API_KEY for the daily-summary function ──────────────────
stage "Groq: daily-summary function secret"
say "The daily-summary Edge Function needs GROQ_API_KEY at runtime. This is a"
say "Supabase function secret (persists on the project, set once) — separate"
say "from the GitHub Actions secrets the rest of this wizard sets."
open_url "https://console.groq.com/keys"
step "Create an API key (free tier covers this feature's volume) and copy it."
ask_secret GROQ_API_KEY "Paste the Groq API key:"
if confirm "Push GROQ_API_KEY to the Supabase function vault now (supabase secrets set --project-ref ${SUPABASE_PROJECT_REF})?"; then
  if supabase secrets set "GROQ_API_KEY=${GROQ_API_KEY}" --project-ref "$SUPABASE_PROJECT_REF"; then
    printf '  %s✓ set%s Supabase function secret GROQ_API_KEY on project %s\n' "$GREEN" "$RESET" "$SUPABASE_PROJECT_REF"
  else
    SKIPPED+=("Supabase function secret GROQ_API_KEY (run: supabase secrets set GROQ_API_KEY=... --project-ref $SUPABASE_PROJECT_REF)")
    warn "supabase secrets set failed; see output above"
  fi
else
  SKIPPED+=("Supabase function secret GROQ_API_KEY (run: supabase secrets set GROQ_API_KEY=... --project-ref $SUPABASE_PROJECT_REF)")
fi

# ── Stage 6: Cloudflare account ID + API token ─────────────────────────────
stage "Cloudflare: account ID + API token"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "On the Workers & Pages overview, copy 'Account ID' from the right sidebar."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID:"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Click 'Create Token', use the 'Edit Cloudflare Pages' template (or a custom"
step "token with Account > Cloudflare Pages > Edit permission)."
step "Copy the token — shown once."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"

# ── Stage 7: Cloudflare Pages project ──────────────────────────────────────
stage "Cloudflare: Pages project"
say "deploy.yml uploads the already-built apps/web/dist directly via wrangler"
say "(not Cloudflare's native git-connected build), so 'Direct Upload' is right."
open_url "https://dash.cloudflare.com/?to=/:account/pages/new/upload"
step "Create a project via 'Direct Upload'. Any placeholder file works for this"
step "first manual creation — the pipeline overwrites it on first real deploy."
step "Note the project name you gave it."
ask CLOUDFLARE_PAGES_PROJECT_NAME "Project name:"
write_env CLOUDFLARE_PAGES_PROJECT_NAME "$CLOUDFLARE_PAGES_PROJECT_NAME"

# ── Stage 8: register GitHub secrets + variable ────────────────────────────
stage "GitHub: register secrets + variable"
say "Writing everything captured above to this repo's GitHub Actions config —"
say "exactly the names deploy.yml reads via secrets.*/vars.*."
set_secret SUPABASE_ACCESS_TOKEN "$SUPABASE_ACCESS_TOKEN"
set_secret SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
set_secret SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret VITE_SUPABASE_URL_PROD "$VITE_SUPABASE_URL_PROD"
set_secret VITE_SUPABASE_ANON_KEY_PROD "$VITE_SUPABASE_ANON_KEY_PROD"
set_var CLOUDFLARE_PAGES_PROJECT_NAME "$CLOUDFLARE_PAGES_PROJECT_NAME"

# ── Stage 9: first migration push ──────────────────────────────────────────
stage "Supabase: apply migrations to production, once"
say "deploy.yml runs 'supabase db push' on every push to main, so this would"
say "happen automatically on the first real deploy. Running it once here first"
say "means credential/connectivity problems surface now, with you watching,"
say "instead of failing mid-pipeline in CI."
note "supabase/migrations/ applies cleanly against Postgres in CI already (packages/db's test suite runs the same files via testcontainers) — this step is about proving the production credentials work, not the migrations themselves."
if confirm "Run 'supabase db push --project-ref ${SUPABASE_PROJECT_REF}' against production now?"; then
  if supabase db push --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"; then
    printf '  %s✓ migrations applied%s to %s\n' "$GREEN" "$RESET" "$SUPABASE_PROJECT_REF"
  else
    warn "supabase db push failed; resolve before pushing to main (deploy.yml would fail the same way)"
  fi
else
  SKIPPED+=("supabase db push --project-ref $SUPABASE_PROJECT_REF --password ... (run by hand, or let the first CI run do it)")
fi

finish
note "Next: push to main. deploy.yml runs lint/test/build, deploys functions +"
note "SPA, and smoke-tests the result — see .scratch/deploy-pipeline/spec.md's"
note "acceptance bar."
